### PR TITLE
Removed harcoded department and branch names :wink:

### LINKED ISSUE #9: Hardcoded Department Names
**Describe the bug**
- The department names are hardcoded in QPapers module as well as Academic Timetable.

**Expected behavior**
- For QPapers, fetch the departments from **DSpace** website and update in SharedPrefs and fetch it when required.
- For Academic Timetable, get the course and department dynamically from [here](https://intranet.cb.amrita.edu/TimeTable/)

### PR DESCRIPTION
**Pull request by sanjailal**
Fetched department and branch names and stored locally using Shared Preferences.
In reference to #9

### CODE REVIEW

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 1]
```diff
@@ -1,303 +1,347 @@
...
+    private void getCourse() {
+        HashMap<String, String> parse = new HashMap<>();
+        parse = initializehashmap(parse);
+        AsyncHttpClient client = new AsyncHttpClient();
+        final HashMap<String, String> finalParse = parse;
+        client.get("https://intranet.cb.amrita.edu/TimeTable/", new AsyncHttpResponseHandler() {
+            @Override
+            public void onSuccess(int i, Header[] headers, byte[] bytes) {
+                Document html = Jsoup.parse(new String(bytes));
+                Elements rows = html.select("center > table").select("tbody>tr").select("td>table").select("tbody>tr").select("td>form").select("select");
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: I think you can keep on chaining directly without using select function.
For example : `center > table > tbody > tr`

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 2]
```diff
@@ -1,303 +1,347 @@
...
+        parse.put("MSc", "MSC");
+        parse.put("Int MA", "IMA");
+        return parse;
+    }
+
+    private void getCourse() {
+        HashMap<String, String> parse = new HashMap<>();
+        parse = initializehashmap(parse);
+        AsyncHttpClient client = new AsyncHttpClient();
+        final HashMap<String, String> finalParse = parse;
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Avoid initialising redundant variables

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 3]
```diff
@@ -1,303 +1,347 @@
...
+        client.get("https://intranet.cb.amrita.edu/TimeTable/", new AsyncHttpResponseHandler() {
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Don't hardcode URLs. Store in strings.xml

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 4]
```diff
@@ -1,303 +1,347 @@
...
+        parse = initializehashmap(parse);
+        AsyncHttpClient client = new AsyncHttpClient();
+        final HashMap<String, String> finalParse = parse;
+        String html ="https://intranet.cb.amrita.edu/TimeTable/funcTimeTable.php?func=drop_1&drop_var="+courses.get(position);
+        client.get(html, new AsyncHttpResponseHandler() {
+            @Override
+            public void onSuccess(int i, Header[] headers, byte[] bytes) {
+                Document html = Jsoup.parse(new String(bytes));
+                Elements rows = html.select("body>select");
+                Log.v("COLUMN", rows.toString());
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Remove logs.

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 5]
```diff
@@ -1,303 +1,347 @@
...
+                for (Element row : rows) {
+                    Elements columns = row.getElementsByTag("option");
+                    Log.v("COLUMN", columns.toString());
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Remove logs everywhere except printing error stack trace.

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 6]
```diff
@@ -1,303 +1,347 @@
...
+        client.get("https://intranet.cb.amrita.edu/TimeTable/", new AsyncHttpResponseHandler() {
+            @Override
+            public void onSuccess(int i, Header[] headers, byte[] bytes) {
+                Document html = Jsoup.parse(new String(bytes));
+                Elements rows = html.select("center > table").select("tbody>tr").select("td>table").select("tbody>tr").select("td>form").select("select");
+                for (Element row : rows) {
+                    Elements columns = row.getElementsByTag("option");
+                    if (columns.get(0).text().equals("Course")) {
+                        for (int j = 1; j < columns.size(); j++) {
+                            String parsedCourse = columns.get(j).text().replace(".", "");
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Try to avoid this when you fetch the HashMap also from the `select` tag : 
image

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 7]
```diff
@@ -1,303 +1,347 @@
...
+
+
+        loadLists();
+        loadFromPref();
+        course.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
+            @Override
+            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
+
+                Gson gson = new Gson();
+                List<String> dummydisplay = new ArrayList<>();
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Use **camelCase** while naming variables.

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 8]
```diff
@@ -1,303 +1,341 @@
...
+            public void onSuccess(int i, Header[] headers, byte[] bytes) {
+                Document html = Jsoup.parse(new String(bytes));
+                Elements rows = html.select("center > table>tbody>tr").select("td>table>tbody>tr>td>form>select");
+                for (Element row : rows) {
+                    Elements columns = row.getElementsByTag("option");
+                    if (columns.get(0).text().equals("Course")) {
+                        for (int j = 1; j < columns.size(); j++) {
+                            String parsedCourse = columns.get(j).attr("value");
+                            courses.add(parsedCourse);
+                        }
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Can you add a `break` statement here ?

Comment (sanjailal) [reply app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Changed to getElementById("#id") and removed the for loop

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 9]
```diff
@@ -1,303 +1,362 @@
...
+    public Spinner year, course, branch, sem, batch;
+    List<String> courses = new ArrayList<>();
+    List<String> branches = new ArrayList<>();
+    List<String> sems = new ArrayList<>();
+    List<String> batches = new ArrayList<>();
+    SharedPreferences pref;
+    SharedPreferences.Editor editor;
+    ArrayAdapter<String> courseAdapter;
+    ArrayAdapter<String> branchAdapter;
+    boolean needupdatecourse;
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Avoid declaring the boolean value.

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 10]
```diff
@@ -1,303 +1,362 @@
...
+            Snackbar.make(view, "Please select all the choices", Snackbar.LENGTH_SHORT).show();
+        }
+    }
+
+    private void buildBranchesSpinner(int courseID) {
+        List<String> branchestemp = new ArrayList<>();
+        branchestemp.add("[Choose branch]");
+        if (!pref.contains(courses.get(courseID))) {
+            needupdatebranch = true;
+            getBranches(courseID, branchestemp);
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Just pass the boolean as a parameter to the getBranches() function and decide to re-populate/not the spinner accordingly.

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 11]
```diff
@@ -1,303 +1,362 @@
...
+                    Snackbar.make(view, "Device not connected to Internet.", Snackbar.LENGTH_SHORT).show();
+                }
+            }
+        } else {
+            Snackbar.make(view, "Please select all the choices", Snackbar.LENGTH_SHORT).show();
+        }
+    }
+
+    private void buildBranchesSpinner(int courseID) {
+        List<String> branchestemp = new ArrayList<>();
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: camelCase bruh :stuck_out_tongue_winking_eye:

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 12]
```diff
@@ -1,303 +1,362 @@
...
+            needupdatebranch = true;
+            getBranches(courseID, branchestemp);
+        } else {
+            branches = new ArrayList<>();
+            Gson gson = new Gson();
+            String json = pref.getString(courses.get(courseID), null);
+            Type listType = new TypeToken<ArrayList<String>>() {
+            }.getType();
+            ArrayList<String> parsedbranch = gson.fromJson(json, listType);
+            branches.addAll(parsedbranch);
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]:
```suggestion
            branches.addAll(gson.fromJson(json, listType));
```
Avoid unnecessary variables.

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 13]
```diff
@@ -1,303 +1,362 @@
...
+            setBranchSpinner();
+            needupdatebranch = false;
+            getBranches(courseID, branchestemp);
+        }
+    }
+
+
+    private void loadLists() {
+        List<String> coursestemp = new ArrayList<>();
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: camelCase again :rocket:

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 14]
```diff
@@ -1,303 +1,362 @@
...
+        coursestemp.add("[Choose course]");
+        if (!pref.contains("courses")) {
+            needupdatecourse = true;
+            getCourse(coursestemp);
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Pass a boolean to the function directly.

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 15]
```diff
@@ -1,303 +1,362 @@
...
+                }
+                Gson gson = new Gson();
+                String coursesjson = gson.toJson(coursestemp);
+                pref.edit().putString("courses", coursesjson).apply();
+                courses = new ArrayList<>();
+                String json = pref.getString("courses", null);
+                Type listType = new TypeToken<ArrayList<String>>() {
+                }.getType();
+                ArrayList<String> course = gson.fromJson(json, listType);
+                courses.addAll(course);
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]:
```suggestion
                courses.addAll(coursesTemp);
```

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 16]
```diff
@@ -1,303 +1,362 @@
...
+        AsyncHttpClient client = new AsyncHttpClient();
+        String html = getString(R.string.branch_name_url) + courses.get(position);
+        client.get(html, new AsyncHttpResponseHandler() {
+            @Override
+            public void onSuccess(int i, Header[] headers, byte[] bytes) {
+                Document html = Jsoup.parse(new String(bytes));
+                Element row = html.getElementById("drop_2");
+                Elements columns = row.getElementsByTag("option");
+                for (int j = 1; j < columns.size(); j++) {
+                    String parsedCourse = columns.get(j).text().replace(".", "");
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Why using text yet ? Use `attr` and get the value directly instead of replacing dots.

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 17]
```diff
@@ -1,303 +1,362 @@
...
+                }
+                Gson gson = new Gson();
+                String branchJson = gson.toJson(branchestemp);
+                pref.edit().putString(courses.get(position), branchJson).apply();
+                branches = new ArrayList<>();
+                String json = pref.getString(courses.get(position), null);
+                Type listType = new TypeToken<ArrayList<String>>() {
+                }.getType();
+                ArrayList<String> branch = gson.fromJson(json, listType);
+                branches.addAll(branch);
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]:
```suggestion
                branches.addAll(branchesTemp);
```

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java (hunk 16 above)
Comment (sanjailal) [reply app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: Will remove the .replace() alone

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java (hunk 11 above)
Comment (sanjailal) [reply app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: :sweat_smile:

File: app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java [hunk 18]
```diff
@@ -1,303 +1,345 @@
...
+                Element row = html.getElementById("drop_1");
+                Elements columns = row.getElementsByTag("option");
+                if (columns.get(0).text().equals("Course")) {
+                    for (int j = 1; j < columns.size(); j++) {
+                        String parsedCourse = columns.get(j).attr("value");
+                        coursesTemp.add(parsedCourse);
+                    }
+                }
+                Gson gson = new Gson();
+                String coursesjson = gson.toJson(coursesTemp);
```
Comment (rajkumaar23) [inline app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: camelCase bro :rofl:

Comment (sanjailal) [reply app/src/main/java/in/co/rajkumaar/amritarepo/timetable/AcademicTimetableActivity.java]: :zipper_mouth_face:

**Comment by rajkumaar23** [comment]
@all-contributors please add @sanjailal for code
